version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:admin@localhost:27017/api-challenge
    networks:
      - api-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-challenge
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:


networks:
  api-network:

volumes:
  mongo-data:
